# Generated by Django 5.1.3 on 2024-11-06 16:41

import core.extra_fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Tiny', 'Крошечный'), ('Small', 'Маленький'), ('Medium', 'Средний'), ('Large', 'Большой')], default='Medium', max_length=6)),
                ('friendliness', core.extra_fields.BreedAttributeField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Дружелюбность, от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Дружелюбность')),
                ('trainability', core.extra_fields.BreedAttributeField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Обучаемость, от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Обучаемость')),
                ('shedding_amount', core.extra_fields.BreedAttributeField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Линючесть, от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Линючесть')),
                ('exercise_needs', core.extra_fields.BreedAttributeField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Нужда в тренировках, от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Нужда в тренировках')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', core.extra_fields.DogCharFieldAttributeField(max_length=100, verbose_name='Пол')),
                ('color', core.extra_fields.DogCharFieldAttributeField(max_length=100, verbose_name='Окрас')),
                ('favorite_food', core.extra_fields.DogCharFieldAttributeField(max_length=100, verbose_name='Любимая еда')),
                ('favorite_toy', core.extra_fields.DogCharFieldAttributeField(max_length=100, verbose_name='Любимая игрушка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
    ]
