# Generated by Django 5.1.3 on 2024-11-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'default_related_name': '%(class)ss', 'ordering': ('id',), 'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'default_related_name': '%(class)ss', 'ordering': ('id',), 'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
    ]
